project:
  type: website
  output-dir: docs

website:
  title: "R & Git Intro"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - Setup.qmd
      - github.qmd
      - r.qmd
      # - wrap-up.qmd
format:
  html:
    toc: true
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    css: styles.css


